# Generated by Django 5.0.7 on 2024-08-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_employee_username_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
