# Generated by Django 5.0.7 on 2024-08-07 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('status', models.CharField(max_length=50)),
                ('estimated_span_in_days', models.IntegerField(default=0)),
                ('employees', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
