# Generated by Django 5.0.7 on 2024-08-08 06:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_employee_hire_date_projectdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field should only contain letters,with no spaces.', regex='^[A-Za-z_]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='This field should only contain letters,with no spaces.', regex='^[A-Za-z_]+$')]),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Description can contain letters, numbers, spaces, and basic punctuation.', regex='^[A-Za-z0-9\\s.,;:!?()-]*$')]),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='This field should only contain letters and underscores, with no spaces.', regex='^[A-Za-z_]+$')]),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='status',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Description can contain letters, numbers, spaces, and basic punctuation.', regex='^[A-Za-z0-9\\s.,;:!?()-]*$')]),
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
